config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root "homes#index"
  match "/admins/products/delete_image_attachment/:id" => "admins/products#delete_image_attachment", via: :get
  resources :homes, only: [:index, :show]


  # get "/new_order", to: "order#new"
  # post "/create_order", to: "orders#create"
  resources :orders 

  namespace :admins do 
    resources :products
    namespace :products do
      post 'csv_upload'
      delete 'delete_image_attachment'
    end
    resources :categories
    resources :orders, only: :index
  end

end

app/models/category.rb
class Category < ApplicationRecord
    has_many :product_categories, dependent: :destroy
    has_many :products, through: :product_categories
end

app/controllers/admins/categories_controller.rb
class Admins::CategoriesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_category, only: %i[ show edit update destroy ]
  layout 'admins'
  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.create(category_params)

    if @category.invalid?
        flash[:error] = @category.errors.full_messages
    end

    redirect_to action: :index
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_admin!, except: [:index, :show]
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.create(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admins/categories/_form.html.erb
<%= form_with model: [:admins, category] do |form| %>
  <div class="mb-4">
    <%= form.label :name, class: "text-grey-darker text-sm font-bold mb-2" %><br>
    <%= form.text_field :name,
        class: "shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker" %>
    <% category.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="action">
    <%= form.submit "Submit", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded cursor-pointer" %>
  </div>
<% end %>

app/views/admins/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', admins_categories_path %>

app/views/admins/categories/index.html.erb
<h1 class="my-6 text-4xl font-bold text-gray-700"> Categories List</h1>
<div class= "my-4">

    <%= link_to "Create New", new_admins_category_path %>

</div>
    <table class="table-auto w-full">
        <thead class="bg-gray-400 uppercase">
            <tr>
                <th class="px-3 py-6 text-left" > Name </th>
                <th class="px-3 py-6 text-center"> Action </th>
            </tr>
        </thead>
        <tbody class="text-sm font-light">
        <% @categories.each do |c| %>
            <tr class="border-b bg-gray-100 hover:bg-gray-200">
                <td class = "px-3 py-6"> <%= c.name %> </td>
                <td class= "px-3 py-6"> 
                    <%= link_to "Show", admins_category_path(c) %> 
                    <%= link_to "Delete", admins_category_path(c), method: :delete %> 
                </td>

            </tr>
        <% end %>
        </tbody>
    </table>

app/views/admins/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', admins_categories_path %>

app/views/admins/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_admins_category_path(@category) %> |
<%= link_to 'Back', admins_categories_path %>