config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root "homes#index"
  match "/admins/products/delete_image_attachment/:id" => "admins/products#delete_image_attachment", via: :get
  resources :homes, only: [:index, :show]


  # get "/new_order", to: "order#new"
  # post "/create_order", to: "orders#create"
  resources :orders 

  namespace :admins do 
    resources :products
    namespace :products do
      post 'csv_upload'
      delete 'delete_image_attachment'
    end
    resources :categories
    resources :orders, only: :index
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_nav.html.erb
<nav class="bg-gray-800 position-absolute inset-0">
    <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
        <div class="relative flex items-center justify-between h-16">
            <div class="flex-1 flex items-center justify-center sm:item-stretch sm:justify-start">
                <div class="flex-shrink-0 flex items-center">
                <%= link_to "Home", homes_path, class:"text-gray-300 rounded-md text-lg font-medium" %>
                </div>
                <div class="hidden sm:block sm:ml-6">
                <div class="flex space-x-4">
                    <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
                    <%= link_to "Product", admins_products_path, class: "nav-link" %>
                    <% if admin_signed_in? %>
                        <%= link_to "Add Product", new_admins_product_path, class: "nav-link"%>
                        <%= link_to "Categories", admins_categories_path, class: "nav-link" %>
                        <%= link_to "Orders", admins_orders_path, class: "nav-link"  %>
                        <%= link_to "Logout", destroy_admin_session_path, method: :delete, class: "nav-link" %>
                    <% else %>
                        <%= link_to "Login", new_admin_session_path , class: "nav-link" %>
                    <% end %>

                    <%= link_to "SignUp", new_admin_registration_path, class: "nav-link" %>                    
                </div>
                </div>
            </div>
        </div>
    </div>
</nav>