config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root "homes#index"
  match "/admins/products/delete_image_attachment/:id" => "admins/products#delete_image_attachment", via: :get
  resources :homes, only: [:index, :show]


  # get "/new_order", to: "order#new"
  # post "/create_order", to: "orders#create"
  resources :orders 

  namespace :admins do 
    resources :products
    namespace :products do
      post 'csv_upload'
      delete 'delete_image_attachment'
    end
    resources :categories
    resources :orders, only: :index
  end

end

app/models/product.rb
class Product < ApplicationRecord
    
    enum status: [:draft, :published, :archived]

    has_one_attached :primary_image
    has_many_attached :images

    has_many :product_categories, dependent: :destroy
    has_many :categories, through: :product_categories

    validates :title, presence: true
    validates :desc, presence: true, length: {minimum:3}
    validates :stock, numericality: { greater_than_or_equal_to: 0 }


end

app/controllers/admins/products_controller.rb
class Admins::ProductsController < ApplicationController
    before_action :authenticate_admin!
    layout 'admins'
    def index
        @products = Product.all

        respond_to do |format|
            format.html {  }
            format.csv { send_data generate_csv(Product.all), file_name: 'products.csv' }
        end

    end

    def show
        @product = Product.find(params[:id])
    end

    def new
        @product = Product.new
        @all_categories = Category.all
        @product_category = @product.product_categories.build
    end

    def edit
        @product = Product.find(params[:id])
    end

    def create
        @product = Product.create(product_params)

        if @product.invalid?
            flash[:error] = @product.errors.full_messages
        end

        redirect_to action: :index
    end

    def update
        @product = Product.find(params[:id])
        @product.update(product_params)
        redirect_to action: :index
    end

    def destroy
        @product = Product.find(params[:id])
        @product.destroy
        redirect_to action: :index
    end

    def csv_upload
        data = params[:csv_file].read.split("\n")
        data.each do |line|
            attribute = line.split(",").map(&:strip)
            Product.create title: attribute[0], desc: attribute[1], stock: attribute[2]
            puts data
        end
        redirect_to action: :index
    end

    def delete_image_attachment
        @product_img = ActiveStorage::Attachment.find(params[:id])
        @product_img.purge
        redirect_to action: :index
    end


    private
    def generate_csv(products)
        products.map { |p| [p.title, p.desc, p.stock].join(',') }.join("\n")
    end

    def product_params
        params.require(:product).permit(:title, :desc, :status, :primary_image, :stock, category_ids: [], images: [])
    end
end

app/controllers/products_controller.rb
# module Admins
    class ProductsController < ApplicationController
        before_action :authenticate_admin!, except: [:index, :show]
    
        def index
            @products = Product.all
    
            respond_to do |format|
                format.html {  }
                format.csv { send_data generate_csv(Product.all), file_name: 'products.csv' }
            end
        end
    
        def show
            @product = Product.find(params[:id])
        end
    
        def new
            @product = Product.new
            @all_categories = Category.all
            @product_category = @product.product_categories.build
        end
    
        def edit
            @product = Product.find(params[:id])
        end
    
        def create
            @product = Product.create(product_params)
    
            if @product.invalid?
                flash[:error] = @product.errors.full_messages
            end
    
            redirect_to action: :index
        end
    
        def update
            @product = Product.find(params[:id])
            @product.update(product_params)
            redirect_to action: :index
        end
    
        def destroy
            @product = Product.find(params[:id])
            @product.destroy
            redirect_to action: :index
        end
    
        def csv_upload
            data = params[:csv_file].read.split("\n")
            data.each do |line|
                attribute = line.split(",").map(&:strip)
                Product.create title: attribute[0], desc: attribute[1], stock: attribute[2]
                puts data
            end
            redirect_to action: :index
        end
    
    
        private
        def generate_csv(products)
            products.map { |p| [p.title, p.desc, p.stock].join(',') }.join("\n")
        end
    
        def product_params
            params.require(:product).permit(:title, :desc, :status, :stock, category_ids: [])
            # params.require(:product).permit(:title, :desc, :status, :stock, :primary_image, category_ids: [])
          end
    end
    
# end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with model: product  do |form| %>
  <div class="mb-4">
    <%= form.label :title, class: "text-grey-darker text-sm font-bold mb-2" %><br>
    <%= form.text_field :title,
        class: "shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker" %>
    <% product.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mb-4">
    <%= form.label :desc, class: "text-grey-darker text-sm font-bold mb-2" %><br>
    <%= form.text_area :desc,
        class: "shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker" %><br>
    <% product.errors.full_messages_for(:desc).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mb-4">
    <%= form.label :stock, class: "text-grey-darker text-sm font-bold mb-2" %><br>
    <%= form.number_field :stock,
        class: "shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker" %>
  </div>
    <% product.errors.full_messages_for(:stock).each do |message| %>
      <div><%= message %></div>
    <% end %>

  <div class="mb-4">
    <%= form.label :status, class: "text-grey-darker text-sm font-bold mb-2" %><br>
    <%= form.select :status, Product.statuses.keys.map { |w| [w.humanize, w] },
    class: "shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker" %>

  </div>

  <div class="mb-4">
    <div class="md:flex flex-col">
            <%= form.label "Categories: ", class: "text-grey-darker text-sm font-bold mb-2" %><br>
            <%= form.collection_check_boxes(
              :category_ids, 
              Category.all, 
              :id, 
              :name, 
              {}, 
              {:class => "inline-block bg-pink-300", multiple: true},
              ) do |b| %>
                <%= b.label(:"data-value" => b.value) { b.check_box+ "  " + b.text }  %>
            <% end %>
    </div>
  </div>

  <div class="action">
    <%= form.submit "Submit", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded cursor-pointer" %>
  </div>


<% end %>

app/views/products/index.html.erb
<h1 class="my-6 text-4xl font-bold text-gray-700"> Products List</h1>

<div>
    <%= link_to "Download CSV", products_path(format: :csv), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded cursor-pointer" %>
</div>

<div class="bg-white shadow-md rounded my-6">
    <table class="table-auto w-full">
        <thead class="bg-gray-400 uppercase">
            <tr>
                <th class="px-3 py-6 text-left" > Pic </th>
                <th class="px-3 py-6 text-left"> title </th>
                <th class="px-3 py-6 text-left"> description </th>
                <th class="px-3 py-6 text-left"> status </th>
                <th class="px-3 py-6 text-left"> catagories </th>
                <th class="px-3 py-6 text-center"> stock </th>
                <th class="px-3 py-6 text-center"> Detail </th>
            </tr>
        </thead>
        <tbody class="text-sm font-light">
        <% @products.each do |p| %>
            <tr class="border-b bg-gray-100 hover:bg-gray-200">
                <td class="px-3 py-6"> 
                    <%= p.id %>
                </td>
                <td class="px-3 py-6"> <%= p.title %> </td>
                <td class="px-3 py-6"> <%= p.desc %> </td>
                <td class="px-3 py-6"> <%= p.status %> </td>
                <td class="px-3 py-6"> <%= p.categories.map(&:name).join(', ') || "NA" %> </td>
                <td class="px-3 py-6 text-center"> <%= p.stock %> </td>
                <td class="px-3 py-6 text-center"> <%= link_to  "Detail" , product_path(p) %> </td>
            </tr>
        <% end %>
        </tbody>
    </table>
</div>

<%= form_with url:products_csv_upload_path, multipart: true do |form| %>

    <div class="image-upload">
        <%= form.file_field :csv_file,
            class: "text-gray-400 py-2 cursor-pointer" %>
        <%= form.submit :upload, 
            class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded cursor-pointer" %>
    </div>



    <%# <label class="w-64 flex flex-col items-center px-4 py-6 bg-white text-blue-500 rounded-lg shadow-lg tracking-wide uppercase border border-blue cursor-pointer hover:bg-blue hover:text-white">
        <svg class="w-8 h-8" fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
            <path d="M16.88 9.1A4 4 0 0 1 16 17H5a5 5 0 0 1-1-9.9V7a3 3 0 0 1 4.52-2.59A4.98 4.98 0 0 1 17 8c0 .38-.04.74-.12 1.1zM11 11h3l-4-4-4 4h3v3h2v-3z" />
        </svg>
        <span class="mt-2 text-base leading-normal">Select a file</span>
        <input type='file' class="hidden" />
    </label> %>
<% end %>

app/views/products/show.html.erb
<h1 class="my-6 text-4xl font-medium text-gray-700"><%= @product.title %></h1>

<p class="text-md "><%= @product.desc %></p>
<p class="text-md ">Stock : <%= @product.stock %></p>
<p class="text-md ">Status : <%= @product.status %></p>

<% if admin_signed_in? %>
<ul class="flex space-x-3 my-6">
  <li >
    <%= link_to "Edit", edit_product_path(@product),
    class: "bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded cursor-pointer" %></li>

  <li>
    <%= link_to "Delete", product_path(@product), 
    method: :delete, data: { confirm: "Delete #{@product.title}?" },
    class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded cursor-pointer" %></li>
</ul>

<% end %>